name: Makefile CI

on:
    push:
        branches: ["dev", "main", "*"]
    pull_request:
        branches: ["dev", "main"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            # - name: configure
            #   run: ./configure

            - name: Install dependencies
              run: make install

            - name: Build
              run: make build

        # - name: Run check
        #   run: make check

        # - name: Run distcheck
        #   run: make distcheck
